### ISSUE TITLE
Cannot paste a geometry into the EDR dialogue

### ISSUE THREAD

**Issue by Gugym** [MetOffice/qgis-plugin-edr#16]
QGIS3.28.6, Plugin version 0.13.1.

When trying to paste a valid geometry into the spatial query extent the dialogue does not allow it

Steps to reproduce:
Open the QGIS Plugin and go to service: https://ogcie.iblsoft.com/edr, select collection GFS - Layer between two depths below land surface and an instance of the data before selecting the data query of trajectory (or other). Try and paste a geometry into the Query spatial extent field.

The user cannot paste a valid geometry into the 'Query spatial extent' field.

**Comment by JanCaha** [comment]
That is by design. The geometry for specific type of query needs to be constructed using tools associated with that query type. Pasting geometry there would rrequire running type checks to ensure that the geometry is valid for the give query type.

**Comment by Gugym** [comment]
Closing - users will input via the 'Set Spatial extent' - there are other issues here that deal with the behaviour there for trajectory ( see for example #21  )
