### ISSUE TITLE
Corridor / Trajectory Query Need Consistency Around Selecting A Pre-Defined Layer

### ISSUE THREAD

**Issue by Gugym** [MetOffice/qgis-plugin-edr#18]
QGIS3.28.6, Plugin version 0.13.1.

When defining a corridor or cube or trajectory query it is not possible to select a pre-existing QGIS layer (as in the area query).

**Comment by JanCaha** [comment]
For these type of queries the whole layer approach would not work, specific feature (or more precisely its geometry) needs to be selected to construct the query.

**Comment by saberraz** [comment]
Replace: `Linestring <not set> ` to `Select an existing line feature`

**Comment by Gugym** [comment]
The following should hopefully make the UI more consistent with QGIS and certainly with the other query types in the plugin. Remove the button for 'Linestring: <NOT SET>' and replace it with the buttons to select either an existing layer, bookmark or layout map. It would be the buttons that have these options: 'Calculate from layer' or 'Layout Map' or 'Bookmark'. This is as shown on an area query. 

The trajectory query also has a 'Corridor Definition' text under it.
Given I have opened the EDR plugin
And I have selected a collection with a trajectory
When I press select spatial extent 
Then I will see the header of 'Trajectory query' (as now)
And then Trajectory definition (it is Corridor definition now)

**Scenario Outline: Make UI Consistent for corridor / trajectory queries**
Given I have the EDR plugin open
And I have a <queryType> selected
When I press the set spatial extent button
Then I will see an option to 'Calculate from layer' or 'Layout Map' or 'Bookmark'
And there will be a button to select another layer
And this will be consistent with the area query
And I will not see a 'Linestring: <NOT SET>' button
Examples:
| queryType |
| corridor |
| trajectory |

**Comment by JanCaha** [comment]
Updated per @saberraz description. Some other updates to GUI regarding these tools.

 But **Then I will see an option to 'Calculate from layer' or 'Layout Map' or 'Bookmark'** does not apply here.
