### ISSUE TITLE
Trajectory/corridor LINESTRING* needs to be in Upper case

### ISSUE THREAD

**Issue by MattWardle** [MetOffice/qgis-plugin-edr#20]
According to[ EDR Spec](https://docs.ogc.org/is/19-086r6/19-086r6.html#_5181b3c7-ada4-40d9-bcf0-4c890a6087f1), 

LINESTRING
LINESTRINGZ
LINESTRINGM
LINESTRINGZM

Needs to be in Upper case. Servers that conform to this are rejecting requests.

**Comment by JanCaha** [comment]
Does this apply only to LINESTRING or should it affect other types of queries as well? 

In general WKT definition should not be size case specific and would be better if the server would handle it without specification of case size.
