### ISSUE TITLE
Don't send datetime when LINESTRING with time included. maybe for Trajectory or corridor - grey out that part of the GUI,

### ISSUE THREAD

**Issue by MattWardle** [MetOffice/qgis-plugin-edr#21]
"datetime" not required for trajectory or corridor - when trajectory or corridor selected as query pattern, suggest disabling temporal extent dialogue.

**Comment by JanCaha** [comment]
If we do that then user will not be able to construct some valid queries according to the spec [https://docs.ogc.org/is/19-086r6/19-086r6.html#_e6b32ddf-d053-46ad-b5fd-c4daec62f4bb](https://docs.ogc.org/is/19-086r6/19-086r6.html#_e6b32ddf-d053-46ad-b5fd-c4daec62f4bb). 

The thing is that user can specify datetime in three ways:

- as part of LINESTRING
- generally as single value outside the scope of LINESTRING
- not use it at all

If we block it in the main window, the user will not be able to to do second version. We may need to gray it out in the main window and add it as part of the Trajectory/Corridor window for user to set the single value and to allow him to not set it at all. 

But I believe that this needs some more thinking and clearer definition of how it should be handled.

**Comment by MattWardle** [comment]
Good point Jan! Yes, let's talk about this tomorrow.

**Comment by m-burgoyne** [comment]
Could it not be solved by checking the WKT string generated by the coordinate definition dialog? 

LINESTRINGM - disable the time selection fields on the main dialog
LINESTRINGZ - disable the vertical selection field on the main dialog
LINESTRINGZM - disable the time and vertical selection fields on the main dialog

**Comment by JanCaha** [comment]
This would work. But we would be missing the part that user does not want to set either time or Z dimension.

**Comment by saberraz** [comment]
If we have temporal values in the Linestring, we should disable temporal extent in the main window.
Same with Z, if we have the Z in Linestring, we need to disable the vertical extent should be disabled.

**Comment by Gugym** [comment]
In the meeting we came up with these scenarios to address this:
Scenario: LINESTRINGM - disable the time selection fields on the main dialog
Given I have an EDR trajectory query 
And I have clicked on the button Set Spatial Extent
When I enter a LINESTRINGM 
Then the main temporal extent selection fields in the ui shall be disabled

Scenario: LINESTRINGZ - disable the vertical selection field on the main dialog
Given I have an EDR trajectory query 
And I have clicked on the button Set Spatial Extent
When I enter a LINESTRINGZ
Then the main vertical extent selection fields in the ui shall be disabled

Scenario: LINESTRINGZM - disable the time and vertical selection fields on the main dialog
Given I have an EDR trajectory query 
And I have clicked on the button Set Spatial Extent
When I enter a LINESTRINGZM 
Then the main temporal and vertical extents selection fields in the ui shall be disabled

Another issue seems to be editing the WKT field when the user can only change a single character at a time. This scenario would be how we expect that to behave:
Given I have an EDR trajectory query 
And I have clicked on the button Set Spatial Extent
And I have selected an existing WKT geometry
When I want to edit the Geometry WKT
Then I can make multiple edits to the WKT 
And I will not have to keep going back into the dialogue after each single character is entered

**Comment by MattWardle** [comment]
Hi Jan, I can't see that this is fixed? Still sends datetime with LINESTRINGM:
![image](https://github.com/MetOffice/qgis-plugin-edr/assets/17428149/c9675dfc-b503-49df-b0bb-63e79165c6d5)

e.g. https://redacted/v4/mo-global/os45/edr/collections/mo-global-zeroisotherm/instances/20240430T120000Z/trajectory?crs=CRS:84&f=CoverageJSON&parameter-name=pressure&**datetime=2024-04-30T12:00:00Z/2024-05-07T12:00:00Z**&z=&coords=**LINESTRINGM** (-3.51327776263088332 50.68829091817624999 1714647634357, -3.02789070332005172 51.28484567251948789 1714658440363, -2.23432138412932657 51.66396246475850518 1714669244650, -0.10786379095806597 51.50598035978200784 1714680049771)

**Comment by Gugym** [comment]
Re-opened with Matt's comment.

**Comment by JanCaha** [comment]
@MattWardle Are you sure, you are on plugin version 0.13.3? Because it seems to be working without issue for me.

Time specified
![Screenshot from 2024-05-03 12-14-10](https://github.com/MetOffice/qgis-plugin-edr/assets/7641902/227164f2-87e5-450e-947b-583aefa9ee24)

Z specified
![Screenshot from 2024-05-03 12-14-45](https://github.com/MetOffice/qgis-plugin-edr/assets/7641902/0b72589d-c4a8-41fb-9d1b-4d9c3d67fc57)

Both T and Z specified
![Screenshot from 2024-05-03 12-15-03](https://github.com/MetOffice/qgis-plugin-edr/assets/7641902/95c8d846-ca4a-42a7-b5dc-16f0aaff2d03)

**Comment by MattWardle** [comment]
Hi Jan, yes i have the latest plugin installed. Oddly it only seems to work properly for that IBL URL. For labs, it also leaves Temporal Extent as an option:
![image](https://github.com/MetOffice/qgis-plugin-edr/assets/17428149/05f2f514-e8c0-492f-9793-d6daa455d5cb)

**Comment by MattWardle** [comment]
![image](https://github.com/MetOffice/qgis-plugin-edr/assets/17428149/eb5e1250-28e2-408e-b27e-f478cddd5f74)

**Comment by MattWardle** [comment]
And now it's broken for IBL as well :-/ Hmm:

LINESTRINGZM (-3.51327776263088332 50.68829091817624999 700 1714777200000, -3.02789070332005172 51.28484567251948789 700 1714798841843, -2.23432138412932657 51.66396246475850518 700 1714820452568, -0.10786379095806597 51.50598035978200784 700 1714842000466)

![image](https://github.com/MetOffice/qgis-plugin-edr/assets/17428149/c98f43d9-3d48-4f66-b021-e0ab254dfb32)
