### ISSUE TITLE
Import GPX with time, timesteps didn't appear in Trajectory dialogue

### ISSUE THREAD

**Issue by MattWardle** [MetOffice/qgis-plugin-edr#22]
[GPX with time.gpx.txt](https://github.com/MetOffice/qgis-plugin-edr/files/15106260/GPX.with.time.gpx.txt)

(had to rename it .txt to be uploaded to Github for some reason).

Created this GPX file on https://gpx.studio/ with time specification. Hoped that those times would be extracted in trajectory dialogue, but it wasn't.
Is this a QGIS import GPX limitation?

**Comment by JanCaha** [comment]
This is a QGIS import limitation. The GPX format is notoriously problematic to get working as the user would like... But this issue is out the scope of this plugin.

**Comment by saberraz** [comment]
[path.gpkg.txt](https://github.com/MetOffice/qgis-plugin-edr/files/15127050/path.gpkg.txt)
@MattWardle could you try this please? (please remove .txt as the extension).

Notes:
You need to use QGIS processing toolbox to set Z and M to the GPX.with.time — track_points and then convert points to path.

GPX is a multi-geometry layer and each piece of information is stored in a separate layer.  By using the following processing tools in QGIS (in order):

- Set M (you need an expression to convert UTC time to epoch)
- Set Z
- Points to path

You can convert it to a single layer to use in the query.

**Comment by MattWardle** [comment]
Hi Saber, yes that works thanks. I'll look into setting a macro. Draw GPX -> Macro -> Trajectory would be nice and easy for the user.

![image](https://github.com/MetOffice/qgis-plugin-edr/assets/17428149/d8d946e9-38de-45b7-9b84-b4a377f78aa8)

**Comment by MattWardle** [comment]
Yes, that's fine @Gugym

**Comment by MattWardle** [comment]
closed
