### ISSUE TITLE
Corridor Query Fails When Attempting To Set Spatial Extent

### ISSUE THREAD

**Issue by Gugym** [MetOffice/qgis-plugin-edr#30]
QGIS 3.28.6 Plugin 13.3

When building a corridor query against the following service an error is triggered when the user clicks on the set spatial extent.

![image](https://github.com/MetOffice/qgis-plugin-edr/assets/4614980/409c99e2-ea93-4c36-92b9-525818f020c0)

2024-05-03T10:31:05     WARNING    Python error : An error has occurred while executing Python code: See message log (Python Error) for more details.
2024-05-03T10:32:26     WARNING    Traceback (most recent call last):
              File "C:\Users/guy.collins/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\edr_plugin\gui\__init__.py", line 496, in set_query_extent
              data_query_tool_cls(self)
              File "C:\Users/guy.collins/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\edr_plugin\gui\query_tools.py", line 499, in __init__
              self.setup_data_query_tool()
              File "C:\Users/guy.collins/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\edr_plugin\gui\query_tools.py", line 518, in setup_data_query_tool
              width_units = corridor_query_data["link"]["variables"]["width_units"]
             KeyError: 'width_units'

This error seems to apply to many different collections on this service.

**Comment by JanCaha** [comment]
Fixed.

But the fix means that the  **https://ogcie.iblsoft.com/edr** will stop working, as it does not provide collection metadata according to the standard  [https://docs.ogc.org/is/19-086r6/19-086r6.html#_e6b32ddf-d053-46ad-b5fd-c4daec62f4bb](https://docs.ogc.org/is/19-086r6/19-086r6.html#_e6b32ddf-d053-46ad-b5fd-c4daec62f4bb).

The variables there (at **ogcie.iblsoft.com**) are named **width_units** and **height_units** but the standard says it should be **width-units** and  **height-units**.

**Comment by Gugym** [comment]
@MattWardle - this needs to be raised to IBL (see comment from Jan above).

**Comment by Gugym** [comment]
This still does not seem to be fixed in version 13.4 of the plugin with QGIS 3.28.6

![image](https://github.com/MetOffice/qgis-plugin-edr/assets/4614980/fdb1e6ee-ffb0-446c-932b-c17c5fb7b1f1)

**Comment by JanCaha** [comment]
This is happening because there is no specification for **height-units** in the collection info. But according to the standard (posted above) the **height-units** is required argument of the Corridor query. It needs to be present in the collection description so that we can use it. Only **width-units** description actually exists for this collection.

**Comment by saberraz** [comment]
To address this issue, it would be good that user receives a clear message what went wrong instead of displaying it in QGIS bug.
