### ISSUE TITLE
Redesign the trajectory window

### ISSUE THREAD

**Issue by saberraz** [MetOffice/qgis-plugin-edr#33]
![image](https://github.com/MetOffice/qgis-plugin-edr/assets/2649047/0aabdec1-4614-4417-b5e0-5d9dbf4ad2b9)

@Gugym to provide a sketch with tooltip and text to update the window for consistency and clarity.

**Comment by Gugym** [comment]
Please find the updated version that is more aligned to the other query UIs. It continues the look and feel whilst not changing the functionality as it currently is. 
<img width="257" alt="QGISTrajectory2a" src="https://github.com/MetOffice/qgis-plugin-edr/assets/4614980/c11502a2-9a05-4082-acbc-2be7d095f782">
